version: '3.1'

services:
  alertwebhook:
    container_name: alertwebhook
    image: alertwebhook:0.8
    build: ./
    ports:
      - 5001:5001
    environment:
      - alertwebhook_dbname=alertwebhook
      - alertwebhook_dbhost=alertwebhook-mysql:3306
      - alertwebhook_servport=:5001
      - alertwebhook_dbuser=root
      - alertwebhook_dbpwd=root
    depends_on:
      alertwebhook-mysql:
        condition: service_healthy
    networks:
      - alertwebhook_net
  alertwebhook-mysql:
    container_name: alertwebhook-mysql
    image: mysql:5.7
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - alertwebhook_net
    ports:
    - 6666:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


networks:
  alertwebhook_net: